package sandbox.sandbox;

/*Generated by MPS */


public class program {

  public static void main(String[] args) {
    int e = 0;
    do {
      fg(e);
      fg2();
      e = increment(e);
    } while (e < 10);
    fg(e);
  }
  public static int fg(int l) {
    System.out.print(l + " ");
    l = Math.abs(l);
    if (l < 10) {
      return l;
    } else if (l < 100) {
      return l - 6;
    } else {
      return l + 100;
    }
  }
  public static String fg2() {
    double v = 5.0;
    System.out.print(v + " ");
    System.out.print("yee" + " ");
    System.out.print("\n");
    return "asd";
  }
  public static int increment(int e) {
    return e + 1;
  }

}
