package sandbox.sandbox;

/*Generated by MPS */

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;

public class program2 {

  public static void main(String[] args) {
    boolean a = false;
    try {
      BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

      String s_r8joyf_b0a = reader.readLine();
      a = s_r8joyf_b0a.toLowerCase().equals("igaz") || s_r8joyf_b0a.equals("1");
    } catch (IOException e_r8joyf_b0a) {
      System.err.println("\nHiba történt az olvasás közben!");
    } catch (IllegalArgumentException e_r8joyf_b0a_0) {
      System.err.println("\nA megadott bemenet nem alaktithato erre a tipusra!");
    }
    if (!(a)) {
      System.out.println("A");
    }
    boolean b = !(true);
    b = !(b);
  }

}
