package sandbox.sandbox;

/*Generated by MPS */


public class program {

  public static void main(String[] args) {
    int e = -10;
    do {
      int k = fg(e);
      System.out.println(k + " " + e);
      fg2();
      e = increment(e, true);
      double c = Math.pow(15, 1/2);
      System.out.print(c);
    } while (e < 10);
    fg(e);
    System.out.print("\n" + "" + Math.pow(e, (2 + 3.01)));
  }
  public static int fg(int l) {
    System.out.print(l);
    l = Math.abs(l);
    if (l <= 10) {
      return l;
    } else if (l < 100) {
      return l - 6;
    } else {
      return l + 100;
    }
  }
  public static String fg2() {
    double v = 5.0;
    System.out.print(v + "" + "yee" + "" + "\n");
    return "asd";
  }
  public static int increment(int e, boolean c) {
    if (c) {
      System.out.println("as");
    }
    return e + 1;
  }

}
