package mePLanG.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ExponentialOperator_Constraints extends BaseConstraintsDescriptor {
  public ExponentialOperator_Constraints() {
    super(CONCEPTS.ExponentialOperator$cX);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ExponentialOperator$cX = MetaAdapterFactory.getConcept(0x4516c44b8ee54276L, 0xbb7f7414c1a20bd0L, 0x134d7de4e5ce2e1cL, "mePLanG.structure.ExponentialOperator");
  }
}
