package mePLanG.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RoutineCallExpression_Constraints extends BaseConstraintsDescriptor {
  public RoutineCallExpression_Constraints() {
    super(CONCEPTS.RoutineCallExpression$TW);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RoutineCallExpression$TW = MetaAdapterFactory.getConcept(0x4516c44b8ee54276L, 0xbb7f7414c1a20bd0L, 0x40e51422f4b5a0b2L, "mePLanG.structure.RoutineCallExpression");
  }
}
