package mePLanG.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PL_Boolean_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PL_Boolean_DataType() {
    super(0x4516c44b8ee54276L, 0xbb7f7414c1a20bd0L, 0x520ab69a10f39cafL, "PL_Boolean_DataType", "r:f23cd24d-0c63-4a47-a186-e2ad0b8a0eaa(mePLanG.structure)/5911738233702816943");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_IGAZ_0 = new EnumerationDescriptor.MemberDescriptor("IGAZ", "IGAZ", 0x520ab69a10f39cc9L, "r:f23cd24d-0c63-4a47-a186-e2ad0b8a0eaa(mePLanG.structure)/5911738233702816969");
  private final EnumerationDescriptor.MemberDescriptor myMember_HAMIS_0 = new EnumerationDescriptor.MemberDescriptor("HAMIS", "HAMIS", 0x520ab69a10f39cb0L, "r:f23cd24d-0c63-4a47-a186-e2ad0b8a0eaa(mePLanG.structure)/5911738233702816944");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x4516c44b8ee54276L, 0xbb7f7414c1a20bd0L, 0x520ab69a10f39cafL, 0x520ab69a10f39cc9L, 0x520ab69a10f39cb0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_IGAZ_0, myMember_HAMIS_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "IGAZ":
        return myMember_IGAZ_0;
      case "HAMIS":
        return myMember_HAMIS_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
